/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_files;

import CODE_files.OnlyNumbers;
import CODE_files.usermodel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gouhar Ali
 */
public class Account_info extends javax.swing.JFrame {

    /**
     * Creates new form Account_info
     */
    
    int xMouse;
    int yMouse;
    public Account_info() {
        initComponents();
        ImageIcon img = new ImageIcon("src/ASSETS_files/pngwing.com.png");
        this.setIconImage(img.getImage());
        getData();
    }
    
    public void getData(){
        usermodel user = new usermodel();
        IDtxt.setText(user.getID());
        NAMEtxt.setText(user.getName());
        USERNAMEtxt.setText(user.getUsername());
        PASSWORDtxt.setText(user.getPassword());
        CODEtxt.setText(user.getCode());
        EMAIL.setText(user.getEmail());
        APP_PASS.setText(user.getAppPass());
        
    }

    
    
    public void update(String field){
        usermodel user = new usermodel();
        
        String newdata=JOptionPane.showInputDialog(this,"ENTER NEW "+field+"");
        
        if(newdata.equals("")){
            JOptionPane.showMessageDialog(this, "ERROR :- Fields empty\n","ERROR",2);
            return;
        }
        
        boolean check = user.update(field, newdata,IDtxt.getText());
        if(check==true){
            JOptionPane.showMessageDialog(this, "SAVED\n"+field+" = "+newdata,"SAVED",1);
            getData();
            return;
        }
        
       
        JOptionPane.showMessageDialog(this, "ERROR :- database error","ERROR",2);
        
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NAMEtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        USERNAMEtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CODEtxt = new javax.swing.JPasswordField();
        PASSWORDtxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        APP_PASS = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("SECURITY CODE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 30));

        IDtxt.setEditable(false);
        IDtxt.setBackground(new java.awt.Color(255, 204, 204));
        IDtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(IDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 340, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NAME");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 30));

        NAMEtxt.setEditable(false);
        NAMEtxt.setBackground(new java.awt.Color(204, 255, 255));
        NAMEtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NAMEtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NAMEtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(NAMEtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 340, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("USERNAME");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 30));

        USERNAMEtxt.setEditable(false);
        USERNAMEtxt.setBackground(new java.awt.Color(204, 255, 255));
        USERNAMEtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USERNAMEtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USERNAMEtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(USERNAMEtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 340, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        CODEtxt.setEditable(false);
        CODEtxt.setBackground(new java.awt.Color(204, 255, 255));
        CODEtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CODEtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CODEtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CODEtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODEtxtActionPerformed(evt);
            }
        });
        CODEtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CODEtxtKeyTyped(evt);
            }
        });
        jPanel3.add(CODEtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 270, 30));

        PASSWORDtxt.setEditable(false);
        PASSWORDtxt.setBackground(new java.awt.Color(204, 255, 255));
        PASSWORDtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PASSWORDtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PASSWORDtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PASSWORDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDtxtActionPerformed(evt);
            }
        });
        jPanel3.add(PASSWORDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 270, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-edit-30.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 40, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-edit-30.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 40, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-edit-30.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 40, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-edit-30.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 40, 30));

        jCheckBox1.setText("SHOW");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 70, 30));

        jCheckBox2.setText("SHOW");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 70, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("ID");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("EMAIL");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 30));

        EMAIL.setEditable(false);
        EMAIL.setBackground(new java.awt.Color(204, 255, 255));
        EMAIL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EMAIL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EMAIL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });
        EMAIL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EMAILKeyTyped(evt);
            }
        });
        jPanel3.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-edit-30.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 40, 30));

        jCheckBox3.setText("SHOW");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 70, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("APP PASSWORD KEY");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 30));

        APP_PASS.setEditable(false);
        APP_PASS.setBackground(new java.awt.Color(204, 255, 255));
        APP_PASS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        APP_PASS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        APP_PASS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        APP_PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APP_PASSActionPerformed(evt);
            }
        });
        APP_PASS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                APP_PASSKeyTyped(evt);
            }
        });
        jPanel3.add(APP_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 270, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-edit-30.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 40, 30));

        jCheckBox4.setText("SHOW");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 70, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 600, 310));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-admin-64.png"))); // NOI18N
        jLabel2.setText("USER INFORMATION");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 620, 460));

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("USER INFO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CODEtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODEtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODEtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         update("CODE");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         update("PASSWORD");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
            PASSWORDtxt.setEchoChar((char)0);
        }else{
            PASSWORDtxt.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void PASSWORDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDtxtActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox1.isSelected()){
            CODEtxt.setEchoChar((char)0);
        }else{
            CODEtxt.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Setting.Skye=0;
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        update("NAME");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        update("USERNAME");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:

        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xMouse , y-yMouse);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void CODEtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CODEtxtKeyTyped
        // TODO add your handling code here:
         new OnlyNumbers().only_numbers(evt);
    }//GEN-LAST:event_CODEtxtKeyTyped

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed

    private void EMAILKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EMAILKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        update("EMAIL");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            EMAIL.setEchoChar((char)0);
        }else{
            EMAIL.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void APP_PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APP_PASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APP_PASSActionPerformed

    private void APP_PASSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APP_PASSKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_APP_PASSKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        update("APP_PASSWORD");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox4.isSelected()){
            APP_PASS.setEchoChar((char)0);
        }else{
            APP_PASS.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField APP_PASS;
    private javax.swing.JPasswordField CODEtxt;
    private javax.swing.JPasswordField EMAIL;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JTextField NAMEtxt;
    private javax.swing.JPasswordField PASSWORDtxt;
    private javax.swing.JTextField USERNAMEtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
