/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_files;
import CODE_files.ConnectDB;
import CODE_files.GetShopInfo;
import CODE_files.Laser_Printer;
import CODE_files.Scale_config_model;
import CODE_files.Thermal_Printer;
import CODE_files.usermodel;
import java.awt.Color;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import zakat.calculator.*;


/**
 *
 * @author Gouhar Ali
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
        ImageIcon img = new ImageIcon("src/ASSETS_files/pngwing.com.png");
        this.setBackground(new Color(0,0,0,0));
        this.setIconImage(img.getImage());
        setAccInfo();
        setShopInfo();
        Scale_config_model scale = new Scale_config_model();
        scale.setScaleDate("1");
        Thermal_Printer tp = new Thermal_Printer();
        tp.setPrinterDate();
        Laser_Printer lp = new Laser_Printer();
        lp.setPinterDate();
        
    }
    
    static int  kye=0;
    
    int xMouse;
    int yMouse;
   
    
    
    public void setAccInfo(){
        usermodel user = new usermodel();
        ACCIDlbl.setText(user.getID());
        ACCNAMElbl.setText(user.getName());
        ACCUSERNAMElbl.setText(user.getUsername());
    }
    
    public void setShopInfo(){
        GetShopInfo shop = new GetShopInfo();
        String []arr=shop.getData();
        SHOPlbl.setText(arr[1]);
        PHONElbl.setText(arr[2]);
        ADDRESSlbl.setText(arr[3]);
    }
    
    
    
    
     
    public static void  showmasseg (){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"A Form is Already open");
    }
    
    
    
    public boolean getAccess(){
        String newdata=JOptionPane.showInputDialog(this, """
                                                         This Section is locked
                                                         ENTER PASSWORD""");
        
        
        if(newdata.equals("") ||newdata==null || !newdata.equals("Khankhan123?") ){
            JOptionPane.showMessageDialog(this, "WRONG PASSWORD");
            return false;
        }else{
         return true;
        }
//        return true;
    }
    
    
    
    public void windowClosing() {

                int confirm = JOptionPane.showConfirmDialog(
                        null,
                        "Are you sure you want to exit?",
                        "Exit Confirmation",
                        JOptionPane.YES_NO_OPTION
                );

                if (confirm == JOptionPane.YES_OPTION) {
                    ConnectDB.closeConnection();   // Close DB safely
                    System.exit(0);
                }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bgpanal1 = new panal.bgpanal();
        pane21 = new panal.pane2();
        jLabel29 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pane11 = new panal.pane1();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        pane12 = new panal.pane1();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ACCUSERNAMElbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ACCIDlbl = new javax.swing.JLabel();
        ACCNAMElbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ADDRESSlbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SHOPlbl = new javax.swing.JLabel();
        PHONElbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        button1 = new ALL_UI_1.Button();
        button2 = new ALL_UI_1.Button();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("  HOME");
        jLabel29.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel29MouseDragged(evt);
            }
        });
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel29MousePressed(evt);
            }
        });
        pane21.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        pane21.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 40));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 40));

        jLabel2.setBackground(new Color(255,255,255,80));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOME");
        jLabel2.setOpaque(true);
        pane11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0,0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-sell-64.png"))); // NOI18N
        jLabel3.setText("SELL GOLD");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        pane11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-purchases-64.png"))); // NOI18N
        jLabel4.setText("RETURN GOLD");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        pane11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 270, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-sell-64.png"))); // NOI18N
        jLabel5.setText("SELL SILVER");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        pane11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-purchases-64.png"))); // NOI18N
        jLabel6.setText("RETURN SILVER");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        pane11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 270, 60));
        pane11.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 10));
        pane11.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 270, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-hammer-64.png"))); // NOI18N
        jLabel7.setText("REPAIR INVOICE");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        pane11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 270, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-order1-64.png"))); // NOI18N
        jLabel8.setText("ORDER INVOICE");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        pane11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 270, 60));
        pane11.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 270, 10));

        bgpanal1.add(pane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 590));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("SHOP DETAIL");
        pane12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 190, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ACCOUNT ID");
        pane12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ACCOUNT NAME");
        pane12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        ACCUSERNAMElbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ACCUSERNAMElbl.setForeground(new java.awt.Color(255, 255, 255));
        ACCUSERNAMElbl.setText("$USERNAME");
        pane12.add(ACCUSERNAMElbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 230, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ACCOUNT USERNAME");
        pane12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        ACCIDlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ACCIDlbl.setForeground(new java.awt.Color(255, 255, 255));
        ACCIDlbl.setText("$ID");
        pane12.add(ACCIDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, 30));

        ACCNAMElbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ACCNAMElbl.setForeground(new java.awt.Color(255, 255, 255));
        ACCNAMElbl.setText("$NAME");
        pane12.add(ACCNAMElbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SHOP");
        pane12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PHONE");
        pane12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 70, 30));

        ADDRESSlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ADDRESSlbl.setForeground(new java.awt.Color(255, 255, 255));
        ADDRESSlbl.setText("$ADDRESS");
        pane12.add(ADDRESSlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 280, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ADDRESS");
        pane12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 90, 30));

        SHOPlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SHOPlbl.setForeground(new java.awt.Color(255, 255, 255));
        SHOPlbl.setText("$SHOP");
        pane12.add(SHOPlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 280, 30));

        PHONElbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PHONElbl.setForeground(new java.awt.Color(255, 255, 255));
        PHONElbl.setText("$PHONE");
        pane12.add(PHONElbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 280, 30));

        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pane12.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("ACCOUNT DETAIL");
        pane12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pane12.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 10, 210));

        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pane12.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 120, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Refresh");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        pane12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 160, 40));

        bgpanal1.add(pane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 810, 290));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-about-20.png"))); // NOI18N
        jLabel18.setText("About Dev");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        bgpanal1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 90, 20));

        button1.setBackground(new java.awt.Color(204, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-setting-64.png"))); // NOI18N
        button1.setText("Setting");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button1.setShadowColor(new java.awt.Color(0, 0, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        bgpanal1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 230, 80));

        button2.setBackground(new java.awt.Color(204, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-logout-30.png"))); // NOI18N
        button2.setText("Logout");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button2.setShadowColor(new java.awt.Color(0, 0, 0));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        bgpanal1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 230, 80));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_jLabel29MousePressed

    private void jLabel29MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseDragged
        // TODO add your handling code here:

        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xMouse , y-yMouse);
    }//GEN-LAST:event_jLabel29MouseDragged

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setOpaque(true);
        jLabel3.setBackground(new Color(242,242,242,100));
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         jLabel3.setOpaque(false);
        jLabel3.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
         jLabel4.setOpaque(true);
        jLabel4.setBackground(new Color(242,242,242,100));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        
         jLabel4.setOpaque(false);
        jLabel4.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel5.setOpaque(true);
        jLabel5.setBackground(new Color(242,242,242,100));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
       jLabel6.setOpaque(true);
        jLabel6.setBackground(new Color(242,242,242,100));
        
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
         jLabel5.setOpaque(false);
        jLabel5.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setOpaque(false);
        jLabel6.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
   
        
        if(kye==0){
            new Gold_sell_invoice().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }
            
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
       
        if(kye==0){
            new Gold_managing().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if(kye==0){
            new Silver_sell_invoice().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
        if(kye==0){
            new Silver_manage().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
        windowClosing();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        setAccInfo();
        setShopInfo();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setOpaque(true);
        jLabel10.setBackground(new Color(242,242,242,100));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
         jLabel10.setOpaque(false);
        jLabel10.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel10MouseExited

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if(kye==0){
            new Setting().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(kye==0){
            dispose();
            new LOGIN().setVisible(true);
            
        }else{
            showmasseg();
                 
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, """
            About Development Team:

            ----------------------------------------
            1)
        Developer  :  Muhammad Uzair.

        Phone No  :  03476442712  (whatsapp only).

        Email          :  iammuhammaduzair5@gmail.com.
        ----------------------------------------
        """,
        "ABOUT DEV",
        JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if(kye==0){
            new MORAMAT().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
        if(kye==0){
            new OrderSystem().setVisible(true);
            kye=1;
            
        }else{
            showmasseg();
                 
        }

        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACCIDlbl;
    private javax.swing.JLabel ACCNAMElbl;
    private javax.swing.JLabel ACCUSERNAMElbl;
    private javax.swing.JLabel ADDRESSlbl;
    private javax.swing.JLabel PHONElbl;
    private javax.swing.JLabel SHOPlbl;
    private panal.bgpanal bgpanal1;
    private ALL_UI_1.Button button1;
    private ALL_UI_1.Button button2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private panal.pane1 pane11;
    private panal.pane1 pane12;
    private panal.pane2 pane21;
    // End of variables declaration//GEN-END:variables
}
