/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_files;

import CODE_files.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gouhar Ali
 */
public class ITEMS extends javax.swing.JFrame {

    /**
     * Creates new form ITEMS
     */
    public ITEMS() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        ImageIcon img = new ImageIcon("src/ASSETS_files/pngwing.com.png");
        this.setIconImage(img.getImage());
        con= new ConnectDB(). Connect();
        Get_Set_Id();
        get_SetData();
        
    }

    int xMouse;
    int yMouse;
    Connection con;
    PreparedStatement str;
    ResultSet rs;
    
    
    public void Get_Set_Id(){
//        
         try{
                    str=con.prepareStatement("SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_NAME = 'items' ");
                    rs=str.executeQuery();
                    if (rs.next()){
                        int id=rs.getInt("AUTO_INCREMENT");
                        IDtxt.setText(""+id);
                    }
                    
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex,"error",2);
        }
        
    }
    
    
    public void get_SetData(){
      try{
          
          str = con.prepareStatement("Select* from items");
          rs=str.executeQuery();
          DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
          df.setRowCount(0);
          while(rs.next()){
            String [] row = {rs.getString("ID"),rs.getString("ITEM"),rs.getString("TYPE")};
            df.addRow(row);
          }
          
      }catch(Exception ex){
          JOptionPane.showMessageDialog(this, ex.getMessage());
      }
    }
    
    
    
    
    public boolean submit(){
        try{
            str = con.prepareStatement("INSERT INTO `items`(`ID`,`ITEM`,TYPE) VALUES (?,?,?)");
            str.setString(1, IDtxt.getText());
            str.setString(2, ITEMtxt.getText());
            str.setString(3, Type_cb.getSelectedItem().toString());
            str.executeUpdate();
            return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",2);
            return false;
        }
    }
    
    
    
    
    public boolean update(){
        try{
            String ID=IDtxt.getText();
            str = con.prepareStatement("UPDATE `items` SET `ITEM`=?,`TYPE`=? WHERE ID="+ID);
            str.setString(1, ITEMtxt.getText());
            str.setString(2, Type_cb.getSelectedItem().toString());
            str.executeUpdate();
            return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",2);
            return false;
        }
    }
    
    
    
    public boolean delete(){
       try{
            String ID=IDtxt.getText();
            str = con.prepareStatement("DELETE FROM `items` WHERE ID="+ID);
            str.executeUpdate();
            return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",2);
            return false;
        }
    }
    
    
    
    public boolean checkSideCase(){
        return IDtxt.getText().equals("") || ITEMtxt.getText().equals("");
    }
    
    
    public void tblClick(){
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        int srow = jTable1.getSelectedRow();
        IDtxt.setText(df.getValueAt(srow, 0).toString());
        ITEMtxt.setText(df.getValueAt(srow, 1).toString());
        Type_cb.setSelectedItem(df.getValueAt(srow, 2).toString());
        saveBtn.setText("UPDATE");    
    }
    
    
    
    public void Newbtn(){
        get_SetData();
        Get_Set_Id();
        ITEMtxt.setText("");
        Type_cb.setSelectedIndex(0);
        saveBtn.setText("SAVE");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        bgpanal21 = new panal.bgpanal2();
        pane21 = new panal.pane2();
        jLabel29 = new javax.swing.JLabel();
        button2 = new ALL_UI_1.Button();
        button1 = new ALL_UI_1.Button();
        jLabel3 = new javax.swing.JLabel();
        bgpanal2 = new panal.bgpanal();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ITEMtxt = new ALL_UI_1.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDtxt = new ALL_UI_1.TextField();
        Type_cb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        button3 = new ALL_UI_1.Button();
        saveBtn = new ALL_UI_1.Button();
        button5 = new ALL_UI_1.Button();

        javax.swing.GroupLayout bgpanal1Layout = new javax.swing.GroupLayout(bgpanal1);
        bgpanal1.setLayout(bgpanal1Layout);
        bgpanal1Layout.setHorizontalGroup(
            bgpanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        bgpanal1Layout.setVerticalGroup(
            bgpanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("  ITEMS");
        jLabel29.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel29MouseDragged(evt);
            }
        });
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel29MousePressed(evt);
            }
        });
        pane21.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        button2.setText("X");
        button2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        button2.setRippleColor(new java.awt.Color(255, 51, 51));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        pane21.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 40));

        button1.setText("-");
        button1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        button1.setRippleColor(new java.awt.Color(204, 255, 204));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pane21.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 40, 40));

        bgpanal21.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jLabel3.setBackground(new java.awt.Color(221, 217, 217));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD ITEMS");
        bgpanal21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 660, 60));

        bgpanal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ITEM", "TYPE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bgpanal2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 320, 340));

        ITEMtxt.setBackground(new java.awt.Color(204, 255, 255));
        ITEMtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ITEMtxt.setShadowColor(new java.awt.Color(0, 0, 0));
        bgpanal2.add(ITEMtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("ID");
        bgpanal2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("ITEM");
        bgpanal2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 50));

        IDtxt.setEditable(false);
        IDtxt.setBackground(new java.awt.Color(255, 204, 204));
        IDtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDtxt.setShadowColor(new java.awt.Color(0, 0, 0));
        bgpanal2.add(IDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 230, 50));

        Type_cb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Type_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SILVER", "GOLD" }));
        bgpanal2.add(Type_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 230, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("TYPE");
        bgpanal2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 50));

        button3.setBackground(new java.awt.Color(255, 204, 204));
        button3.setText("DELETE");
        button3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button3.setShadowColor(new java.awt.Color(0, 0, 0));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        bgpanal2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 130, 50));

        saveBtn.setBackground(new java.awt.Color(204, 255, 204));
        saveBtn.setText("SAVE");
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        saveBtn.setShadowColor(new java.awt.Color(0, 0, 0));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        bgpanal2.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 320, 50));

        button5.setBackground(new java.awt.Color(204, 255, 255));
        button5.setText("NEW");
        button5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button5.setShadowColor(new java.awt.Color(0, 0, 0));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        bgpanal2.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, 50));

        bgpanal21.add(bgpanal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 680, 380));

        getContentPane().add(bgpanal21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel29MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseDragged
        // TODO add your handling code here:

        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xMouse , y-yMouse);
    }//GEN-LAST:event_jLabel29MouseDragged

    private void jLabel29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_jLabel29MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        tblClick();
    }//GEN-LAST:event_jTable1MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        Setting.Skye=0;

        dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:

        this.setState(ICONIFIED);
    }//GEN-LAST:event_button1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
         Newbtn();
    }//GEN-LAST:event_button5ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        
        if(checkSideCase()==true){
            JOptionPane.showMessageDialog(this, "empty fields","ERROR",2);
            return;
        }
        if(saveBtn.getText().equals("SAVE")){
            JOptionPane.showMessageDialog(this, "Unable to delete","ERROR",2);
            return;
        }
        int check = JOptionPane.showConfirmDialog(this, "Are you sure", "Deleting item", JOptionPane.YES_NO_OPTION);
        if(check==0){
            delete();
            Newbtn();
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here: 
        if(checkSideCase()==true){
            JOptionPane.showMessageDialog(this, "empty fields","ERROR",2);
            return;
        }
        if(saveBtn.getText().equals("SAVE")){
            submit();
            Newbtn();
            return;
        }
        if(saveBtn.getText().equals("UPDATE")){
            update();
            Newbtn();
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITEMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ALL_UI_1.TextField IDtxt;
    private ALL_UI_1.TextField ITEMtxt;
    private javax.swing.JComboBox<String> Type_cb;
    private panal.bgpanal bgpanal1;
    private panal.bgpanal bgpanal2;
    private panal.bgpanal2 bgpanal21;
    private ALL_UI_1.Button button1;
    private ALL_UI_1.Button button2;
    private ALL_UI_1.Button button3;
    private ALL_UI_1.Button button5;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private panal.pane2 pane21;
    private ALL_UI_1.Button saveBtn;
    // End of variables declaration//GEN-END:variables
}
