/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_files;

import CODE_files.ConnectDB;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class loding extends javax.swing.JFrame {

 
    Connection con;
    PreparedStatement str;
    ResultSet rs;
    
   
    public loding() {
        initComponents();
        ImageIcon img = new ImageIcon("src\\ASSETS_files\\pngwing.com.png");
        this.setIconImage(img.getImage());
        
    }

    
    public boolean checktrials(){
        try{
           
            
                str=con.prepareStatement("select* from trial where ID=1");
                rs=str.executeQuery();
                if(rs.next()){
                    int d=rs.getInt("day");
                    int m=rs.getInt("month");
                    int y=rs.getInt("year");
                    if(m==1){
                        m=12;
                    }else{
                        m--;
                    }
                    
                    Calendar expireDate = Calendar.getInstance();               
                    // when identify month January take as  0 (y, m, d)
                    expireDate.set(y, m, d); // set expire date you need
                       // Get current date and compare
                    if (Calendar.getInstance().after(expireDate))
                    {
                        return false;
                    }
                    return true;
                }
            return false;
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,  "ERROR:-\n"+ex.getMessage());
            return false;
        }
        
    }
    
    
    
    
    
    
    
    public boolean checkActive(){
        try{
            str=con.prepareStatement("select* from software_status where status='activated' and Id=1");
            rs=str.executeQuery();
            if(rs.next()){
                return true;
            }
            return false;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "ERROR:- cant check system activation","Error",2);
            return false;
        }
       
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lodingbar = new javax.swing.JProgressBar();
        lodevalue = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(227, 225, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/pngwing.com.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 250));

        lodingbar.setBackground(new java.awt.Color(204, 255, 255));
        lodingbar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lodingbar.setForeground(new java.awt.Color(51, 51, 255));
        lodingbar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lodingbar.setFocusable(false);
        jPanel1.add(lodingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 550, 20));

        lodevalue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lodevalue.setForeground(new java.awt.Color(255, 0, 102));
        lodevalue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lodevalue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lodevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 50, 30));

        msg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msg.setForeground(new java.awt.Color(0, 51, 255));
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 500, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WELCOME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PLEASE WAIT.....");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 230, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Jewelery Shop Management System");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 550, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 462));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
               
            loding s=new loding();
            s.setVisible(true);
            try{
                   for(int i=0;i<=100;i++){
                       Thread.sleep(60);
                       s.lodevalue.setText(i+"%");
                       if (i<10){
                           s.msg.setText("LODING");
                       }
                       if (i==10){
                          s.msg.setText("PLEASE WAIT CONNECTING");
                          try{
                               Process process = Runtime.getRuntime().exec("\\C:\\xampp\\mysql\\bin\\mysqld.exe");
                          }catch(Exception e)
                          {
                               s.msg.setText("DATABASE NOT FOUND");
                               JOptionPane.showMessageDialog(s,"DATABASE NOT FOUND\n"+e,"Database Error",2);
                               System.exit(0);
                          }
                       }
                       if (i==20){
                           
                           s.msg.setText("CONNECTING TO DATABASE");
                         
                       }
                       
                       if (i==40){
                           s.con= new ConnectDB().Connect();
                           if(s.con==null){
                                JOptionPane.showMessageDialog(s,"DATABASE NOT Connected","Database Error",2);
                                System.exit(0);
                           }
                           s.msg.setText("DATABASE CONNECTED");
                       }
                       if (i>70){
                           s.msg.setText("CHECKING SYSTEM ACTIVATION");
                           
                       }
                       
                       
                       if(i==100){
                           
                           
                           if(s.checkActive()==false){
                              if(s.checktrials()==false){
                                JOptionPane.showMessageDialog(s, """
                                                                 Sorry Free Triel Ended
                                                                 Please buy system key
                                                                 Thank you
                                                                 """);
                                new AfterExp().setVisible(true);
                                s.dispose();
                                return;
                              }else{
                                s.dispose();
                                new NotExp().setVisible(true);
                                return;
                              }
                           }
                           
                           
                           s.dispose();
                           LOGIN l = new LOGIN();
                           l.setVisible(true);
                       }
                       s.lodingbar.setValue(i);
                       
                   }
                   
            }catch(Exception e){
                   JOptionPane.showMessageDialog(s, e);
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lodevalue;
    private javax.swing.JProgressBar lodingbar;
    private javax.swing.JLabel msg;
    // End of variables declaration//GEN-END:variables
}
