/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_files;

import CODE_files.Laser_Printer;
import CODE_files.Scale_config_model;
import CODE_files.Thermal_Printer;
import javax.swing.JOptionPane;

/**
 *
 * @author Gouhar Ali
 */
public class Printer_config extends javax.swing.JFrame {

    /**
     * Creates new form Printer_config
     */
    public Printer_config() {
        initComponents();
        setThermalPrinter();
        setLaserPrinter();
    }
    
    
    
    public void setThermalPrinter(){
        Thermal_Printer tp = new Thermal_Printer();
        TP_ID.setText(""+tp.getPrinter_id());
        TP_NAME.setText(""+tp.getPrinter_name());
        TP_TYPE.setText(""+tp.getPrinter_type());
        
    }
    
    public void setLaserPrinter(){
        Laser_Printer lp = new Laser_Printer();
        LP_ID.setText(""+lp.getPrinter_id());
        LP_NAME.setText(""+lp.getPrinter_name());
        LP_TYPE.setText(""+lp.getPrinter_type());
    }
    
    
    
    
    
    
    public void updateThermalBtn(String field ,String id){
        Thermal_Printer tp = new Thermal_Printer();
        
        String newdata=JOptionPane.showInputDialog(this,"ENTER NEW "+field+"");
        
        if(newdata.equals("")){
            JOptionPane.showMessageDialog(this, "ERROR :- Fields empty\n","ERROR",2);
            return;
        }
        
        boolean check = tp.update(field, newdata,id);
        if(check==true){
            JOptionPane.showMessageDialog(this, "SAVED\n"+field+" = "+newdata,"SAVED",1);
            setThermalPrinter();
            return;
        }
        
        JOptionPane.showMessageDialog(this, "ERROR :- database error","ERROR",2);
        
    }
    
    
    public void updateLaserBtn(String field ,String id){
        Laser_Printer lp = new Laser_Printer();
        
        String newdata=JOptionPane.showInputDialog(this,"ENTER NEW "+field+"");
        
        if(newdata.equals("")){
            JOptionPane.showMessageDialog(this, "ERROR :- Fields empty\n","ERROR",2);
            return;
        }
        
        boolean check = lp.update(field, newdata,id);
        if(check==true){
            JOptionPane.showMessageDialog(this, "SAVED\n"+field+" = "+newdata,"SAVED",1);
            setLaserPrinter();
            return;
        }
        
        JOptionPane.showMessageDialog(this, "ERROR :- database error","ERROR",2);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal22 = new panal.bgpanal2();
        pane22 = new panal.pane2();
        button1 = new ALL_UI_1.Button();
        jLabel1 = new javax.swing.JLabel();
        pane21 = new panal.pane2();
        LP_TYPE = new ALL_UI_1.TextField();
        LP_NAME = new ALL_UI_1.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LP_ID = new ALL_UI_1.TextField();
        jLabel8 = new javax.swing.JLabel();
        button8 = new ALL_UI_1.Button();
        pane23 = new panal.pane2();
        TP_TYPE = new ALL_UI_1.TextField();
        TP_NAME = new ALL_UI_1.TextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TP_ID = new ALL_UI_1.TextField();
        jLabel9 = new javax.swing.JLabel();
        button9 = new ALL_UI_1.Button();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgpanal22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(new java.awt.Color(255, 204, 204));
        button1.setText("X");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pane22.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 40, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Printer Configuration");
        pane22.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        bgpanal22.add(pane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        LP_TYPE.setEditable(false);
        LP_TYPE.setBackground(new java.awt.Color(255, 204, 204));
        LP_TYPE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LP_TYPE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LP_TYPE.setShadowColor(new java.awt.Color(0, 0, 0));
        pane21.add(LP_TYPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 280, 60));

        LP_NAME.setEditable(false);
        LP_NAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LP_NAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LP_NAME.setShadowColor(new java.awt.Color(0, 0, 0));
        pane21.add(LP_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 280, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Printer Type");
        pane21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Printer Name");
        pane21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID");
        pane21.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 60));

        LP_ID.setEditable(false);
        LP_ID.setBackground(new java.awt.Color(255, 204, 204));
        LP_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LP_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LP_ID.setShadowColor(new java.awt.Color(0, 0, 0));
        pane21.add(LP_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 280, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("A5 Laser printer");
        pane21.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        button8.setText("UPDATE");
        button8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button8.setShadowColor(new java.awt.Color(0, 0, 0));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        pane21.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 120, 60));

        bgpanal22.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 600, 230));

        TP_TYPE.setEditable(false);
        TP_TYPE.setBackground(new java.awt.Color(255, 204, 204));
        TP_TYPE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TP_TYPE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TP_TYPE.setShadowColor(new java.awt.Color(0, 0, 0));
        pane23.add(TP_TYPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 280, 60));

        TP_NAME.setEditable(false);
        TP_NAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TP_NAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TP_NAME.setShadowColor(new java.awt.Color(0, 0, 0));
        pane23.add(TP_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 280, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Printer Type");
        pane23.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Printer Name");
        pane23.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ID");
        pane23.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 60));

        TP_ID.setEditable(false);
        TP_ID.setBackground(new java.awt.Color(255, 204, 204));
        TP_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TP_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TP_ID.setShadowColor(new java.awt.Color(0, 0, 0));
        pane23.add(TP_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 280, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("80mm thermal printer");
        pane23.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        button9.setText("UPDATE");
        button9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button9.setShadowColor(new java.awt.Color(0, 0, 0));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        pane23.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 120, 60));

        bgpanal22.add(pane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 600, 230));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-printer-80.png"))); // NOI18N
        jLabel10.setText("Manage Printers");
        bgpanal22.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 600, 100));
        bgpanal22.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 620, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanal22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanal22, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        
        updateLaserBtn("NAME",LP_ID.getText());
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        
        updateThermalBtn("NAME",TP_ID.getText());
    }//GEN-LAST:event_button9ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printer_config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printer_config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printer_config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printer_config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Printer_config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ALL_UI_1.TextField LP_ID;
    private ALL_UI_1.TextField LP_NAME;
    private ALL_UI_1.TextField LP_TYPE;
    private ALL_UI_1.TextField TP_ID;
    private ALL_UI_1.TextField TP_NAME;
    private ALL_UI_1.TextField TP_TYPE;
    private panal.bgpanal2 bgpanal22;
    private ALL_UI_1.Button button1;
    private ALL_UI_1.Button button8;
    private ALL_UI_1.Button button9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private panal.pane2 pane21;
    private panal.pane2 pane22;
    private panal.pane2 pane23;
    // End of variables declaration//GEN-END:variables
}
