/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_files;

import CODE_files.Scale_config_model;
import CODE_files.usermodel;
import com.fazecast.jSerialComm.SerialPort;
import javax.swing.JOptionPane;

/**
 *
 * @author Gouhar Ali
 */
public class Scale_Config extends javax.swing.JFrame {

    
    public Scale_Config() {
        initComponents();
        set_ComPort();
        
        getData();
        
            
        
        
    }

    
    public void getData(){
        Scale_config_model scale = new Scale_config_model();
        com_list.setSelectedItem(scale.getCom());
        baud_rate.setText(""+scale.getBaud_rate());
        no_of_bits.setText(""+scale.getBits());
        stop_bits.setText(""+scale.getStop_bits());
    }
    
    
    
     public void set_ComPort(){  
            SerialPort[] ports = SerialPort.getCommPorts();
            System.out.println("Available COM ports:");
            for (SerialPort port : ports) {
                com_list.addItem(port.getSystemPortName());
            }
    } 
     
     
    public void updateBtn(String field){
        Scale_config_model scale = new Scale_config_model();
        
        String newdata=JOptionPane.showInputDialog(this,"ENTER NEW "+field+"");
        
        if(newdata.equals("")){
            JOptionPane.showMessageDialog(this, "ERROR :- Fields empty\n","ERROR",2);
            return;
        }
        
        boolean check = scale.update(field, newdata,"1");
        if(check==true){
            JOptionPane.showMessageDialog(this, "SAVED\n"+field+" = "+newdata,"SAVED",1);
            getData();
            return;
        }
        
        JOptionPane.showMessageDialog(this, "ERROR :- database error","ERROR",2);
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        com_list = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        baud_rate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        no_of_bits = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stop_bits = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-weight-light-100.png"))); // NOI18N
        jLabel1.setText("SCALE  CONNECTION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BAUD RATE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, 30));

        com_list.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(com_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECT COM#");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 30));

        baud_rate.setEditable(false);
        baud_rate.setBackground(new java.awt.Color(255, 204, 204));
        baud_rate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        baud_rate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(baud_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NO OF BITS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 240, 30));

        no_of_bits.setEditable(false);
        no_of_bits.setBackground(new java.awt.Color(255, 204, 204));
        no_of_bits.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        no_of_bits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(no_of_bits, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("STOP BITS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 30));

        stop_bits.setEditable(false);
        stop_bits.setBackground(new java.awt.Color(255, 204, 204));
        stop_bits.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stop_bits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(stop_bits, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 240, 40));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 90, 40));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, 40));

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 90, 40));

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updateBtn("BITS");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String com = com_list.getSelectedItem().toString();
        
        Scale_config_model scale = new Scale_config_model();
        scale.update("COM", com, "1");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        updateBtn("BAUD_RATE");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        updateBtn("STOP_BITS");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scale_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scale_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scale_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scale_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scale_Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baud_rate;
    private javax.swing.JComboBox<String> com_list;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField no_of_bits;
    private javax.swing.JTextField stop_bits;
    // End of variables declaration//GEN-END:variables
}
